version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    #restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - db-mysql:/var/lib/mysql
    networks:
      - app-network  # Certifique-se de que o MySQL está na rede

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: security-api
    #restart: always
    ports:
      - "80:80"
    environment:
      DB_HOST: "mysql"  # Alterado para o nome do serviço MySQL
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_DATABASE: "core_db"
    depends_on:
      - mysql
    networks:
      - app-network  # A aplicação também deve estar na mesma rede

networks:
  app-network:

volumes:
  db-mysql: