version: '3.8'
services:
  superset:
    image: amancevice/superset
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: '2a3e0ea0-2ef5-4928-ab52-22fb482e621e'
      SUPERSET_ADMIN_USERNAME: 'admin'
      SUPERSET_ADMIN_PASSWORD: 'admin'
      DATABASE_DB: 'superset'
      DATABASE_HOST: "${DB_PROVIDER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASE_USER: "${DB_USERNAME}"
      DATABASE_PORT: "${DB_PORT}"
      DATABASE_DIALECT: "${DB_PROVIDER}"
    volumes:
      - ./superset/superset_config.py:/etc/superset/superset_config.py
      - ./superset/jwt_security.py:/etc/superset/jwt_security.py
    ports:
      - "8088:8088"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - db-mysql:/var/lib/mysql

volumes:
  db-mysql: