name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm install

      - name: Gerar Build
        run: npm run build

      - name: Testar Build
        run: npm test

      - name: Fazer Deploy
        run: |
          # Seu comando de deploy, como:
          scp -r ./build user@your-server:/path/to/app
          ssh user@your-server "cd /path/to/app && npm install --production && pm2 restart app"